### PR TITLE
send isAdmin to the frontend for protecting routes

### PR DESCRIPTION
**Pull request by karthikkrishna1**
Modified the login function in accountController to send isAdmin, a boolean indicating if a user is an admin or not to the frontend.

### CODE REVIEW

**Comment by dscwebdev** [comment]
Could you lmk what formatter you are using, I we might want to look into enforcing prettier or some other kind of format on save for all future devs

**Comment by karthikkrishna1** [comment]
Oh, I use prettier

**Comment by karthikkrishna1** [comment]
Made the changes. please check

**Review by Bobby2500 — APPROVED** [review]
LGTM ! Merge whenever

**Pull request merged**
